name: Fetch data

on:
  push:
    branches: [main]
  schedule:
    # Run at 3am on Monday, Thursday, and Saturday
    - cron: "0 3 * * 1,4,6"
  workflow_dispatch:

jobs:
  tweets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"
      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          # Install CPU-based pytorch
          pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
      - name: Main script
        run: |
          python3 -m pip install -r requirements.txt
          python3 ./src/tweets.py
        env:
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "output/tweets"

  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"
      - name: Main script
        run: |
          python3 -m pip install requests
          python3 ./src/stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/stats"
