name: Github Stats

on:
  push:
    branches: [main]
  schedule:
    # Run at 3am on Monday, Thursday, and Saturday
    - cron: "0 3 * * 1,4,6"
  workflow_dispatch:

jobs:
  
  stats:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"
      - name: Main script
        run: |
          python3 -m pip install requests
          python3 ./src/stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/stats"
          push: origin main --force