name: Lunar Crush Stats

on:
  push:
    branches: [main]
  schedule:
    # Run at 3am on Monday, Thursday, and Saturday
    - cron: "0 3 1 * *"
  workflow_dispatch:

jobs:
  
  lunar-crush:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"
      - name: Main script
        run: |
          python3 -m pip install requests
          python3 ./src/social_score.py
        env:
          LUNARCRUSH_TOKEN: ${{ secrets.LUNARCRUSH_TOKEN }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/social-score"
          push: origin main --force
